### ISSUE TITLE
Plex Provider + web cast

### ISSUE THREAD

**Issue by julientaverne** [pedromsilvapt/unicast#25]
Hi, great Job!
Can you please tell me if you plan to add a new provider like Plex (plex.tv) ?
Can you alse please tell me if it possible to read movies, ... in another way for chromecast: with my chrome browser ?
Thank you.
Best Regards,
Julien Taverne.

**Comment by pedromsilvapt** [comment]
Hi, thanks for your interest in the app.

Unfortunately, this project is being done in my spare time (which is not much) and for personal use. I still have a lot of things that I need to do before I could consider adding other functionality (such as more providers).

However, the project is already very flexible, and anyone with knowledge of Node.JS/Typescript can create new providers for whatever sources they want.

As for your second question, I'm not sure I understand. Yes, Chrome can cast videos to Chromecast ([as shown here](https://support.google.com/chromecast/answer/7249696?hl=en-IN)) by opening the video file with Chrome. However, it has to be in a format that Chrome understands, if I'm not mistaken.
